apiVersion: v1
kind: Secret
metadata:
  name: backend-app-secret
type: Opaque
stringData:
  DB_USERNAME: a_nice_user
  DB_PASSWORD: a_very_complex_password
  DB_HOST: qlik-postgres
  DB_PORT: "5432"
  DB_NAME: awesome_database
  DB_SSLMODE: disable
  ALLOWED_ORIGIN: '*'
